"""AI Workstation — Request Context Graph (v0.4.0)

Every request carries a RequestContext through the middleware pipeline.
Each stage appends a StageResult to the execution_trace array.

v0.4.0 additions:
  - queue_wait_time_ms: time spent waiting in the request queue
  - worker_id: ID of the worker that processed this request
  - pipeline_mode: "strict" | "optimized"
  - latency_breakdown: dict with queue, routing, exec, audit timings
  - policy_decision_graph: list of (policy_id, decision) for this request

Mandatory fields:
  - request_id: unique identifier for the request
  - session_id: session context identifier
  - project_id: project isolation scope
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional


PIPELINE_STRICT = "strict"
PIPELINE_OPTIMIZED = "optimized"


@dataclass
class StageResult:
    """Immutable result from a single pipeline stage.

    Attributes:
        stage: stage name (e.g. "pre_validation", "session_guard")
        decision: "allow" | "deny" | "skip"
        duration_ms: wall-clock time for this stage
        detail: arbitrary stage-specific metadata
        error: error message if decision == "deny" (None otherwise)
        timestamp: ISO 8601 timestamp of stage completion
    """

    stage: str
    decision: str
    duration_ms: float
    detail: Dict[str, Any] = field(default_factory=dict)
    error: Optional[str] = None
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def as_dict(self):
        return {
            "stage": self.stage,
            "decision": self.decision,
            "duration_ms": round(self.duration_ms, 3),
            "detail": self.detail,
            "error": self.error,
            "timestamp": self.timestamp,
        }


@dataclass
class ErrorEnvelope:
    """Structured error envelope for tool isolation failures.

    Used when a tool execution is stopped by timeout or caught exception.
    Never raises — always returned as a structured result.
    """

    code: str
    message: str
    trace: Optional[str] = None
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def as_dict(self):
        return {
            "status": "error",
            "result": None,
            "error": self.message,
            "error_code": self.code,
            "error_trace": self.trace,
            "duration_ms": 0,
        }


@dataclass
class RequestContext:
    """Structured request context carried through the pipeline.

    Mandatory fields (validated at construction):
      - request_id: autogenerated if not provided
      - session_id: required — violates PreValidation if empty
      - project_id: required — violates PreValidation if empty

    Populated by pipeline stages:
      - tool_id: set by CapabilityRouting stage
      - capability: original capability string
      - arguments: tool arguments dict
      - execution_trace: ordered StageResult list
      - decision_path: ordered stage names visited
      - stage_timings: dict[stage_name, ms]

    Final state:
      - status: "success" | "error" | "denied"
      - timestamp_start / timestamp_end: lifecycle boundaries
      - result: tool execution result (if status == "success")
      - error: error message (if status == "error" or "denied")
    """

    request_id: str
    session_id: str
    project_id: str
    tool_id: Optional[str] = None
    capability: Optional[str] = None
    arguments: Dict[str, Any] = field(default_factory=dict)
    execution_trace: List[StageResult] = field(default_factory=list)
    decision_path: List[str] = field(default_factory=list)
    stage_timings: Dict[str, float] = field(default_factory=dict)
    status: str = "pending"
    timestamp_start: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    timestamp_end: Optional[str] = None
    result: Optional[Any] = None
    error: Optional[str] = None
    error_code: Optional[str] = None

    queue_wait_time_ms: float = 0.0
    worker_id: str = ""
    pipeline_mode: str = PIPELINE_STRICT
    latency_breakdown: Dict[str, float] = field(default_factory=dict)
    policy_decision_graph: List[Dict[str, Any]] = field(default_factory=list)

    @staticmethod
    def create(raw_request: dict) -> RequestContext:
        """Factory: create RequestContext from a raw JSON request dict."""
        request_id = raw_request.get("id") or f"auto_{uuid.uuid4().hex[:8]}"
        session_data = raw_request.get("session", {})
        params = raw_request.get("params", {})

        mode = raw_request.get("pipeline_mode", PIPELINE_STRICT)
        if mode not in (PIPELINE_STRICT, PIPELINE_OPTIMIZED):
            mode = PIPELINE_STRICT

        return RequestContext(
            request_id=request_id,
            session_id=session_data.get("session_id", "") or "",
            project_id=session_data.get("project_id", "") or "",
            tool_id=params.get("tool"),
            capability=params.get("capability"),
            arguments=params.get("arguments", {}),
            pipeline_mode=mode,
        )

    def finalize(self, status: str, result=None, error=None, error_code=None):
        """Mark the request lifecycle as complete."""
        self.status = status
        self.result = result
        self.error = error
        self.error_code = error_code
        self.timestamp_end = datetime.now(timezone.utc).isoformat()

    def add_trace(self, stage_result: StageResult):
        """Append a stage result to the execution trace."""
        self.execution_trace.append(stage_result)
        self.decision_path.append(stage_result.stage)
        self.stage_timings[stage_result.stage] = stage_result.duration_ms

    def current_stage(self) -> Optional[str]:
        """Return the last completed stage name, or None."""
        if self.decision_path:
            return self.decision_path[-1]
        return None

    def was_denied(self) -> bool:
        """Check if any stage issued a deny decision."""
        for trace in self.execution_trace:
            if trace.decision == "deny":
                return True
        return False

    def full_trace(self) -> List[Dict[str, Any]]:
        """Return the full execution trace as a list of serializable dicts."""
        return [t.as_dict() for t in self.execution_trace]

    def as_response(self) -> dict:
        """Build the unified gateway response from the context."""
        response = {
            "id": self.request_id,
            "status": self.status,
            "tool_id": self.tool_id,
            "session": {
                "session_id": self.session_id,
                "project_id": self.project_id,
            },
            "execution": {
                "pipeline_mode": self.pipeline_mode,
                "worker_id": self.worker_id,
                "queue_wait_time_ms": round(self.queue_wait_time_ms, 3),
                "stages": self.full_trace(),
                "decision_path": self.decision_path,
                "total_ms": round(
                    sum(self.stage_timings.values()), 3
                ) if self.stage_timings else 0,
                "latency_breakdown": self.latency_breakdown,
                "timestamp_start": self.timestamp_start,
                "timestamp_end": self.timestamp_end,
            },
            "policy_graph": self.policy_decision_graph,
        }

        if self.result is not None:
            response["result"] = self.result
        if self.error:
            response["error"] = {"code": self.error_code or "ERROR", "message": self.error}
        if self.error_code:
            response["error_code"] = self.error_code

        return response
